### ISSUE TITLE
There is something going on with include path. include_lib for the compiled app is not resolved.

### ISSUE THREAD

**Issue by ikvmw** [rabbitmq/rules_erlang#100]
If I have an app with path like this: include/header.hrl. I can reference it as `include_lib("myapp/include/header.hrl") or include("header.hrl"). This doesn't work with bazel currently.
Example: https://github.com/tsloughter/grpcbox/blob/main/src/grpcbox_health_client.erl

See docs here: https://www.erlang.org/doc/reference_manual/macros.html

**Comment by pjk25** [comment]
Things are not currently set up by convention for a module do include its own headerfile, as if it is a separate library. That seems to be what's going on in this library, which isn't something I've seen before.

According to the docs:
> If the filename File is absolute (possibly after variable substitution), the include file with that name is included. Otherwise, the specified file is searched for in the following directories, and in this order:

> 1. The current working directory
> 2. The directory where the module is being compiled
> 3. The directories given by the include option

In the case of `grpcbox`, `grpcbox/include/grpcbox.hrl` is not probably not a valid path for 1 or for 2, and really I would not expect it to be 3.

It's rather unfortunate, as it amounts to a self-dependency at the app level. I think there is a workaround - you can pass an appropriate `erlc_opts` value that would allow the header to be found.

**Comment by pjk25** [comment]
So, it was kindly pointed out to me that I missed some of the docs:

> include_lib is similar to include, but is not to point out an absolute file. Instead, the first path component (possibly after variable substitution) is assumed to be the name of an application.

So from that I think it's reasonable to try to support this, probably as a special case for header files.

**Comment by pjk25** [comment]
"Self includes" are now supported in [v3.8.4](https://github.com/rabbitmq/rules_erlang/releases/tag/3.8.4)
