### ISSUE TITLE
Gazelle language extension

### ISSUE THREAD

**Issue by pjk25** [rabbitmq/rules_erlang#103]
Provide a [gazelle language extension](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.md) for erlang

This work has already been started in #94

**Comment by lixen-wg2** [comment]
Hi we are currently looking into improving our bazel setup for for erlang and this looks very promising.

How would I go about trying out https://github.com/rabbitmq/rules_erlang/pull/94?

**Comment by pjk25** [comment]
Things are still a work and progress, and undocumented, but you are welcome to try it.

`WORKSPACE.bazel`:

```starlark
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "rules_erlang",
    branch = "experimental-gazelle-extension",
    remote = "https://github.com/rabbitmq/rules_erlang.git",
)

load("@rules_erlang//:internal_deps.bzl", "rules_erlang_internal_deps")

rules_erlang_internal_deps()

load("@rules_erlang//:internal_setup.bzl", "rules_erlang_internal_setup")

rules_erlang_internal_setup()

load("@rules_erlang//gazelle:deps.bzl", "gazelle_deps")

gazelle_deps()

load("@rules_erlang//:rules_erlang.bzl", "erlang_config")

erlang_config()

load("@erlang_config//:defaults.bzl", "register_defaults")

register_defaults()
```

and add to your root level `BUILD.bazel`:

```starlark
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@rules_erlang//gazelle:def.bzl", "GAZELLE_ERLANG_RUNTIME_DEPS")

gazelle(
    name = "gazelle",
    data = GAZELLE_ERLANG_RUNTIME_DEPS,
    gazelle = "@rules_erlang//gazelle:gazelle_erlang_binary",
)

# gazelle:erlang_generate_beam_files_macro
```

Then run `bazel run gazelle -- --verbose`.

You can also try out `bazel run //:gazelle -- update-repos --verbose [name]=hex.pm/[package]@[version] to add deps from hex.pm to your workspace.

If you are also trying out `bzlmod`, you will need to use a bazel 6 rc. For that I use bazelisk.

**Comment by pjk25** [comment]
If your code uses behaviors from external deps, you will need to hint to gazelle their location with a gazelle directive, such as

```
# gazelle:erlang_behaviour_source_lib ranch_protocol:ranch
```

**Comment by lixen-wg2** [comment]
Thanks, will give it a try.

**Comment by pjk25** [comment]
https://github.com/rabbitmq/rules_erlang/releases/tag/3.9.0 is out with the first version of the extension, so I will close this.
