### ISSUE TITLE
Hello World example

### ISSUE THREAD

**Issue by Vertexwahn** [rabbitmq/rules_erlang#111]
Would it be possible to add a minimal "Hello World" example in the documentation?

I tried it here, but did not get it working:
https://stackoverflow.com/questions/74709415/erlang-hello-world-using-bazel-as-a-build-system

**Comment by pjk25** [comment]
A response was posted in stackoverflow: https://stackoverflow.com/a/75007131/20928572

Something similar was raised in https://github.com/rabbitmq/rules_erlang/issues/32, however it's slightly different, which was part of my hesitation in assuming a singular expecattion for what `bazel run //:erlang_app` would actually mean.
