### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rules_erlang#17]
Should this project be named `rules_erlang`?

There seems to be a convention in place - https://github.com/bazelbuild

https://github.com/bazelbuild/rules_rust

**Comment by pjk25** [comment]
Maybe yes. I thought that I had looked around for conventions when I created it. Maybe I missed those. Or maybe I had started off with the intention of actually doing the otp build directly in bazel. I'd be fine with changing it.

**Comment by lukebakken** [comment]
Great. Maybe someday we can get this added to github.com/bazelbuild
