### ISSUE TITLE
Merge `native.glob` values in `app.bzl` files

### ISSUE THREAD

**Issue by HoloRin** [rabbitmq/rules_erlang#185]
### Is your feature request related to a problem? Please describe.

These values don't get updated, and when a new behaviour is introduced, it's not correctly excluded from `:other_beam` properly

### Describe the solution you'd like

Add extra logic to merge these values

**Comment by pjk25** [comment]
It turned out to be more sensible overall to just not generate the wildcards, so I will consider this "fixed" by #187
