### ISSUE TITLE
no matching toolchains found for types @rules_erlang//tools:toolchain_type

### ISSUE THREAD

**Issue by ramkumarr** [rabbitmq/rules_erlang#52]
Hi,
Just for trying out ```rules_erlang```, I have this in my ```WORKSPACE```:

```starlark
...
load("@rules_erlang//:rules_erlang.bzl", "rules_erlang_dependencies")
rules_erlang_dependencies()
register_toolchains("@rules_erlang//:erlang_toolchain_external",)

new_git_repository(
    name = "proper",
    build_file_content = """load("@rules_erlang//:erlang_app.bzl", "erlang_app")
erlang_app(
    app_name = "proper",
    app_version = "1.4",
)
""",
    remote = "https://github.com/proper-testing/proper",
    tag = "v1.4",
)
...
```

If I try to build this target, I get
```
ERROR: /root/.cache/bazel/_bazel_root/5482c3378a07db53297479e5e3a1767b/external/proper/BUILD.bazel:2:11:
While resolving toolchains for target @proper//:beam_files: no matching toolchains found for types @rules_erlang//tools:toolchain_type
ERROR: Analysis of target '//:build' failed; build aborted:
```

Is there something more I should do to register a toolchain correctly? I do have a working Erlang installation.
(Bazel version - 5.1.1, rules_erlang version - 3.1.0, Ubuntu with a standard Erlang install through apt)

**Comment by pjk25** [comment]
My guess is that you have not selected an erlang platform, which is essential for resolving the toolchain.

Have you created a `.bazelrc` file similar to the following mentioned in the readme?

```starlark
build --@rules_erlang//:erlang_home=/path/to/erlang
build --@rules_erlang//:erlang_version=23.2

build --platforms=@rules_erlang//platforms:erlang_external_platform
build --extra_execution_platforms=@rules_erlang//platforms:erlang_external_platform
```

Make sure to replace the erlang home dir and the version with whatever is correct for your system. If you just have one erlang installed, and aren't using something like kerl, you can find erlang home with `ERLANG_HOME="$(dirname $(dirname $(which erl)))"`

**Comment by ramkumarr** [comment]
I had the erlang_home, erlang_version and platform in my bazelrc, but I missed the extra_execution_platform - it seems that is a requirement as well - adding that lets me proceed, but only a bit further.. Now I get

```
ERROR: /root/.cache/bazel/_bazel_root/5482c3378a07db53297479e5e3a1767b/external/rules_erlang/BUILD.bazel:23:26:
 Validating otp at /usr/lib/erlang failed: (Exit 1): bash failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/5482c3378a07db53297479e5e3a1767b/sandbox/linux-sandbox/5/execroot/__main__ && \
  exec env - \
  /bin/bash -c 'set -euo pipefail

beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
V=$("/usr/lib/erlang"/bin/erl -eval '\''{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().'\'' -noshell)
if ! beginswith "22.2.7" "$V"; then
echo "Erlang version mismatch (Expected 22.2.7, found $V)"
exit 1
fi

echo "$V" >> bazel-out/aarch64-opt-exec-2AD51420/bin/external/rules_erlang/otp_external_version
')
# Configuration: 57e66a3c502015c96e660bd4481181cd958897a569ae2a04dd067a88967dc264
# Execution platform: @rules_erlang//platforms:erlang_external_platform

Use --sandbox_debug to see verbose messages from the sandbox
erlexec: HOME must be set
```

I do have ```--incompatible_strict_action_env``` (and also ```--action_env=HOME```) in my .bazelrc, but it seems HOME is not set in the action's ```run_shell``` invocation. Should the ```run_shell``` in ```private/erlang_build.bzl: _erlang_external_impl``` have ```use_default_shell_env=True```?

**Comment by ramkumarr** [comment]
I tried patching ```_erlang_external_impl``` definition with an explicit env, like this:
```starlark
         ),
         mnemonic = "OTP",
         progress_message = "Validating otp at {}".format(erlang_home),
+       env = {"HOME": "/root",},
     )
```

Indeed, with this patch, I can build the library. If I patch all the ```ctx.action.run_shell``` in ```rules_erlang```, then I can also run xref, dialyzer etc. But surely, this must be unnecessary?

**Comment by pjk25** [comment]
You should not have to patch it, no. It seems like you are running as root? This is not something I have tested. You might try adjusting your bazelrc to include `--action_env HOME=/root` rather than just `--action_env HOME`. It should have the same effect as your patches.

**Comment by pjk25** [comment]
Also, I may not have tested with Erlang 22, and I'm not sure that having HOME set is required on erlang 23+.

**Comment by pjk25** [comment]
Since there has not been any news on this issue recently, I will close it.
