### ISSUE TITLE
Bad interop with asdf

### ISSUE THREAD

**Issue by illotum** [rabbitmq/rules_erlang#80]
Since d40f85e ERLANG_HOME needs to be manually set by all `asdf` users, since the tool hides all binaries behind a shim:

```
valiushk@3c22fb6527ee ~> which erl
/Users/valiushk/.asdf/shims/erl
valiushk@3c22fb6527ee ~> asdf where erlang
/Users/valiushk/.asdf/installs/erlang/25.1
```

`which` in general can be easily misled, what if you used `code:root_dir()`?

```
erl -noshell -eval 'io:format("~s",[code:root_dir()]),init:stop().'
```

**Comment by pjk25** [comment]
For clarification, would those users have previously used `--@rules_erlang//:erlang_home=/Users/valiushk/.asdf/installs/erlang/25.1`, and the env var is less convenient than `.bazelrc`?

Using `@erlang_config` is optional, but I do see there is room for better detection of the erlang installation root

**Comment by pjk25** [comment]
Should be improved/fixed with https://github.com/rabbitmq/rules_erlang/releases/tag/3.7.1

**Comment by illotum** [comment]
Quick turnaround, thanks! 

Yes, previously I controlled it with `@rules_erlang`in rabbit's user.bazerlc, but followed the new template to remove the clause.
