### ISSUE TITLE
Question: How to use rules_erlang for building elixir

### ISSUE THREAD

**Issue by Kruemelmann** [rabbitmq/rules_erlang#91]
Hey I read about this repo in [rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server/blob/main/BAZEL.md#why-rabbitmq--bazel).
Now I wanted to ask if you could implement a small example or write some docs on how to use these rules for building elixir.

**Comment by pjk25** [comment]
Hi, Elixir support is still a work in progress, and is effectively embedded in rabbitmq-server at this time:
https://github.com/rabbitmq/rabbitmq-server/tree/main/bazel/elixir
https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/rabbitmqctl.bzl
https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/rabbitmqctl_test.bzl

It's not as clean as we would like, so it has not yet been extracted into an official `rules_elixir` repository.

**Comment by Kruemelmann** [comment]
Hi @pjk25 Thanks for your fast reply. Is that extraction planted in the near future and are you interested in pull requests or contribution in such rules_elixir repository. I would be happy to help with this if you are interessted.

**Comment by pjk25** [comment]
I don't think we have plans to extract it in the near future. It's working well enough for rabbitmq-server, so it's not a near term priority. `mix` has not been easy to integrate with the bazel model, so I wanted to slow down and think about it a bit before attempting a general approach. In particular, feeding precompiled dependencies into `mix` is not something I've figured out how to do smoothly.

No `rules_elixir` repository exists in our org yet (or anywhere else as far as I know). If you were interested in creating one, we'd probably look into using it, but with less urgency that the pure erlang side of things.

**Comment by Kruemelmann** [comment]
Alright thanks again:) I am closing this issue as answerd.

**Comment by pjk25** [comment]
Thanks for raising it. We would definitely like to have a `rules_elixir`, I just want to be realistic about the when.
